apiVersion: apps/v1
kind: Deployment
metadata:
  name: hcl-playground-development
  labels:
    app: hcl-playground-development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hcl-playground-development
  template:
    metadata:
      labels:
        app: hcl-playground-development
    spec:
      containers:
      - name: hcl-playground-development
        image: {{IMAGE_NAME}}
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: hcl-playground-volume
            mountPath: /scratch
        securityContext:
          runAsGroup: 1000
      initContainers:
        - name: fs-owner-change
          image: busybox
          command: [ 'sh', '-c', 'chown root:1000 /scratch && chmod 777 /scratch' ]
          volumeMounts:
            - name: hcl-playground-volume
              mountPath: /scratch
      securityContext:
        fsGroup: 1000
      volumes:
        - name: hcl-playground-volume
          persistentVolumeClaim:
              claimName: efs-pvc