apiVersion: v1
kind: Service
metadata:
  name: hcl-playground-development
spec:
  selector:
    app: hcl-playground-development
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80