apiVersion: v1
kind: Service
metadata:
  name: hcl-playground-development
  annotations:
    # TODO: get this dynamically
    service.beta.kubernetes.io/aws-load-balancer-arn: "arn:aws:elasticloadbalancing:us-east-1:386710959426:loadbalancer/app/hcl-playground-lb/2975a2897854dc77"
  selector:
    app: hcl-playground-development
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
  externalTrafficPolicy: Cluster