apiVersion: v1
kind: Service
metadata:
  name: hcl-playground-development
  annotations:
    # TODO: fetch these dynamically
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:386710959426:certificate/e4698b03-63d5-4133-a18a-7b692a41afd9"

    service.beta.kubernetes.io/aws-load-balancer-ssl-protocols: "TLSv1.2"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"

spec:
  selector:
    app: hcl-playground-development
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
  externalTrafficPolicy: Cluster