version: 2.1
orbs:
  aws-eks: circleci/aws-eks@volatile
  aws-ecr: circleci/aws-ecr@volatile

jobs:
  build-and-push-image:
    executor: aws-ecr/default
    parameters:
      ecr_repo_name:
        type: string
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          repo: <<parameters.ecr_repo_name>>
          tag: '${CIRCLE_SHA1}'
          dockerfile: Dockerfile

  deploy-to-eks:
    executor: aws-eks/python3
    parameters:
      eks_cluster_name:
        type: string
    steps:
      - checkout
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: <<parameters.eks_cluster_name>>
      - run:
          name: Replace image name in Kubernetes deployment file
          command: |
            sed -i 's|{{IMAGE_NAME}}|123456789012.dkr.ecr.us-east-1.amazonaws.com/my-app-repo:${CIRCLE_SHA1}|' ./k8s/deployment.yaml
      - run:
          name: Deploy to EKS
          command: |
            kubectl apply -f deployment/k8s/deployment.yaml
            kubectl apply -f deployment/k8s/service.yaml

  setup-infrastructure:
    docker:
      - image: hashicorp/terraform:light
    parameters:
      auto_approve:
        type: boolean
        default: false
      project_path:
        type: string
    steps:
      - checkout
      - terraform/init:
          path: <<parameters.project_path>>/
      - terraform/plan:
          path: <<parameters.project_path>>/
          var: "TF_VAR_subdomain_from_env='${CIRCLE_SHA1}'"
      - terraform/apply:
          path: <<parameters.project_path>>/
          auto_approve: <<parameters.auto_approve>>
          var: "TF_VAR_subdomain_from_env='${CIRCLE_SHA1}'"

workflows:
  build-deploy-dev:
    jobs:
      - setup-infrastructure:
          auto_approve: true
          project_path: deployment/terraform/development
      - build-and-push-image:
          requires:
            - setup-infrastructure
      - deploy-to-eks:
          requires:
            - build-and-push-image
    filters:
      branches:
        not:
          - main